// ===========================================================================
// ФАЙЛ: data.js
// НАЗНАЧЕНИЕ: Хранилище данных пользователей.
// ===========================================================================

console.log('📦 data.js загружен');

const appTitle = "Список пользователей";

const usersData = [
  {
    id: 1,
    surname: "Малыгина",
    name: "Анна",
    patronymic: 'Владимировна',
    email: "anna@list.ru",
    phone: "+7 (925) 782-96-23",
    birthDate: "02-01-2027",
    deathDate: "",
    city: "Москва",
    profession: "Дизайнер",
    gender: "female",
  },
  {
    id: 2,
    surname: "Попов",
    name: "Иван",
    patronymic: "Фёдорович",
    email: "125Sina@mail.ru",
    phone: "+7 (965) 896-02-75",
    birthDate: "02-05-1795",
    deathDate: "12-11-1850",
    city: "Санкт-Петербург",
    profession: "Разработчик",
    gender: "male",
  },
  {
    id: 3,
    surname: "Самсонова",
    name: "Мария",
    patronymic: "Филлиповна",
    email: "36_Mari@list.com",
    phone: "+7 (914) 866-05-96",
    birthDate: "26-02-1987",
    deathDate: "19-02-1995",
    city: "Южно-Сахалинск",
    profession: "Маркетолог",
    gender: "female",
  },
  {
    id: 4,
    surname: "Аракчеев",
    name: "Алексей",
    patronymic: "Дмитриевич",
    email: "Alex_Ar@mail.ru",
    phone: "+7 (966) 285-77-00",
    birthDate: "10-10-2005",
    deathDate: "",
    city: "Новосибирск",
    profession: "Аналитик",
    gender: "male",
  },
  {
    id: 5,
    surname: "Бугров",
    name: "Николай",
    patronymic: "Александрович",
    email: "avindialit@list.ru",
    phone: "701-20-41",
    birthDate: "15-03-1837",
    deathDate: "16-04-1911",
    city: "Нижний Новгород",
    profession: "Маркетолог",
    gender: "male",
  },
  {
    id: 6,
    surname: "Курчатов",
    name: "Игорь",
    patronymic: "Васильевич",
    email: "",
    phone: "2-45-67",
    birthDate: "12-01-1903",
    deathDate: "07-02-1960",
    city: "Челябинск-40",
    profession: "Разработчик",
    gender: "male",
  },
  {
    id: 7,
    surname: "Дуров",
    name: "Валерий",
    patronymic: "Семёнович",
    email: "durov@spb.su",
    phone: "123-45-67",
    birthDate: "05-07-1945",
    deathDate: "",
    city: "Ленинград",
    profession: "Аналитик",
    gender: "male",
  },
  {
    id: 8,
    surname: "Иванова",
    name: "Елена",
    patronymic: "Петровна",
    email: "elena.ivanova@gmail.com",
    phone: "+7 (812) 987-65-43",
    birthDate: "22-09-1995",
    deathDate: "",
    city: "Санкт-Петербург",
    profession: "Дизайнер",
    gender: "female",
  },
  {
    id: 9,
    surname: "Семёнова",
    name: "Пелагея",
    patronymic: "Ильинична",
    email: "",
    phone: "",
    birthDate: "10-01-1905",
    deathDate: "15-03-2015",
    city: "Красноярск",
    profession: "Учитель",
    gender: "female",
  },
  {
    id: 10,
    surname: "Сидоров",
    name: "Пётр",
    patronymic: "Иванович",
    email: "",
    phone: "",
    birthDate: "15-05-1980",
    deathDate: "01-01-2045",   // будущая дата смерти (например, осуждённый)
    city: "Москва",
    profession: "Разработчик",
    gender: "male",
  }
];

console.log('   usersData загружен, пользователей:', usersData.length);